services:
  mongodb:
    image: mongo:latest
    container_name: poc
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PWD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_LOCAL_PORT}:${DB_PORT}
    volumes:
      - ./init.db:/docker-entrypoint-initdb.d
      - ./data:/data/db
      - ./logs:/var/log/mongodb
